
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: catalogo_filme_api_development

test:
  <<: *default
  database: catalogo_filme_api_test

production:
  <<: *default
  database: catalogo_filme_api_production
  username: catalogo_filme_api
  password: <%= ENV["CATALOGO_FILME_API_DATABASE_PASSWORD"] %>
